from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 176, 245);")
        self.label.setObjectName("label")
        self.null1 = QtWidgets.QPushButton(self.centralwidget)
        self.null1.setGeometry(QtCore.QRect(0, 300, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.null1.setFont(font)
        self.null1.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.null1.setObjectName("null1")
        self.justice = QtWidgets.QPushButton(self.centralwidget)
        self.justice.setGeometry(QtCore.QRect(150, 300, 81, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.justice.setFont(font)
        self.justice.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.justice.setObjectName("justice")
        self.num7 = QtWidgets.QPushButton(self.centralwidget)
        self.num7.setGeometry(QtCore.QRect(0, 224, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num7.setFont(font)
        self.num7.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num7.setObjectName("num7")
        self.num4 = QtWidgets.QPushButton(self.centralwidget)
        self.num4.setGeometry(QtCore.QRect(0, 150, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num4.setFont(font)
        self.num4.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num4.setObjectName("num4")
        self.num1 = QtWidgets.QPushButton(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(0, 80, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num1.setFont(font)
        self.num1.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num1.setObjectName("num1")
        self.num8 = QtWidgets.QPushButton(self.centralwidget)
        self.num8.setGeometry(QtCore.QRect(77, 224, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num8.setFont(font)
        self.num8.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num8.setObjectName("num8")
        self.num5 = QtWidgets.QPushButton(self.centralwidget)
        self.num5.setGeometry(QtCore.QRect(77, 150, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num5.setFont(font)
        self.num5.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num5.setObjectName("num5")
        self.num2 = QtWidgets.QPushButton(self.centralwidget)
        self.num2.setGeometry(QtCore.QRect(77, 80, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num2.setFont(font)
        self.num2.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QPushButton(self.centralwidget)
        self.num3.setGeometry(QtCore.QRect(153, 80, 77, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num3.setFont(font)
        self.num3.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num3.setObjectName("num3")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(230, 150, 71, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.plus.setObjectName("plus")
        self.num9 = QtWidgets.QPushButton(self.centralwidget)
        self.num9.setGeometry(QtCore.QRect(153, 224, 77, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num9.setFont(font)
        self.num9.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num9.setObjectName("num9")
        self.num6 = QtWidgets.QPushButton(self.centralwidget)
        self.num6.setGeometry(QtCore.QRect(153, 155, 77, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.num6.setFont(font)
        self.num6.setStyleSheet("background-color: rgb(255, 126, 217);")
        self.num6.setObjectName("num6")
        self.exactly = QtWidgets.QPushButton(self.centralwidget)
        self.exactly.setGeometry(QtCore.QRect(230, 227, 70, 73))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.exactly.setFont(font)
        self.exactly.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.exactly.setObjectName("exactly")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(230, 80, 71, 77))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.minus.setObjectName("minus")
        self.multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.multiplication.setGeometry(QtCore.QRect(230, 300, 70, 79))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.multiplication.setFont(font)
        self.multiplication.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.multiplication.setObjectName("multiplication")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_justice = False


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculater"))
        self.label.setText(_translate("MainWindow", "0"))
        self.null1.setText(_translate("MainWindow", "0"))
        self.justice.setText(_translate("MainWindow", "="))
        self.num7.setText(_translate("MainWindow", "7"))
        self.num4.setText(_translate("MainWindow", "4"))
        self.num1.setText(_translate("MainWindow", "1"))
        self.num8.setText(_translate("MainWindow", "8"))
        self.num5.setText(_translate("MainWindow", "5"))
        self.num2.setText(_translate("MainWindow", "2"))
        self.num3.setText(_translate("MainWindow", "3"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.num9.setText(_translate("MainWindow", "9"))
        self.num6.setText(_translate("MainWindow", "6"))
        self.exactly.setText(_translate("MainWindow", "/"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multiplication.setText(_translate("MainWindow", "*"))

    def add_functions(self):
        self.null1.clicked.connect(lambda: self.write_number(self.null1.text()))
        self.num1.clicked.connect(lambda: self.write_number(self.num1.text()))
        self.num2.clicked.connect(lambda: self.write_number(self.num2.text()))
        self.num3.clicked.connect(lambda: self.write_number(self.num3.text()))
        self.num4.clicked.connect(lambda: self.write_number(self.num4.text()))
        self.num5.clicked.connect(lambda: self.write_number(self.num5.text()))
        self.num6.clicked.connect(lambda: self.write_number(self.num6.text()))
        self.num7.clicked.connect(lambda: self.write_number(self.num7.text()))
        self.num8.clicked.connect(lambda: self.write_number(self.num8.text()))
        self.num9.clicked.connect(lambda: self.write_number(self.num9.text()))
        self.exactly.clicked.connect(lambda: self.write_number(self.exactly.text()))
        self.plus.clicked.connect(lambda: self.write_number(self.plus.text()))
        self.minus.clicked.connect(lambda: self.write_number(self.minus.text()))
        self.multiplication.clicked.connect(lambda: self.write_number(self.multiplication.text()))
        
        self.justice.clicked.connect(self.result)

    def write_number(self, number):
        if self.label.text() == "0" or self.is_justice:
            self.label.setText(number)
            self.is_justice = False
        else:
            self.label.setText(self.label.text() + number)

    def result(self):
        if not self.is_justice:
            res = eval(self.label.text())
            self.label.setText("Результат: " + str(res))
            self.is_justice = True
        else:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Сейчас это выполнить нельзя")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Reset|QMessageBox.Ok|QMessageBox.Cancel)

            error.setDefaultButton(QMessageBox.Ok)
            error.setInformativeText("Два раза действие не выполнить")
            error.setDetailedText("Детали")

            error.buttonClicked.connect(self.popup_action)

            error.exec_()
    
    def popup_action(self, btn):
        if btn.text() == "Ok":
            print("Ok")
        elif btn.text() == "Reset":
            self.label.setText("")
            self.is_justice = False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
